# Copyright (c) 2022, the Dart project authors.  Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

name: jnigen
version: 0.4.0-dev
description: Experimental generator for FFI+JNI bindings.
repository: https://github.com/dart-lang/jnigen/tree/main/jnigen

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  json_annotation: ^4.8.0
  package_config: ^2.1.0
  path: ^1.8.0
  args: ^2.3.0
  yaml: ^3.1.0
  logging: ^1.0.2
  meta: ^1.8.0
  cli_config: ^0.1.0

dev_dependencies:
  lints: ^2.0.0
  jni:
    path: ../jni
  test: ^1.24.1
  build_runner: ^2.2.0
  json_serializable: ^6.6.0
