name: pdfbox_plugin
description: |
  Example of using jnigen to generate bindings for a non-trivial Java library.
version: 0.0.1
publish_to: none
homepage: https://github.com/dart-lang/jnigen

environment:
  sdk: ">=2.17.6 <3.0.0"
  #flutter: ">=2.11.0"

dependencies:
  jni:
    path: ../../../jni/
  #flutter:
    #sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ## Path dependency for sake of the example
  jnigen:
    path: ../../
  test: any
  lints: ^2.0.0

flutter:
  # A JNI plugin uses FFI for calling into C code. Thus the relevant shared
  # library artifacts must be bundled with final application.
  # Please refer to README.md for a detailed explanation.
  plugin:
    platforms:
      android:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true

